### ISSUE TITLE
Inkscape Tutorial 7

### ISSUE THREAD

**Issue by candideu** [Roy-Torley/Roy-Torley.github.io#4]
Hi Roy!

I found your [Inkscape Tutorial 7](https://roy-torley.github.io/Inkscape_Tutorial/Tutorial07/Tutorial07.html) while looking for the Free Transform Tool equivalent in Inkscape. Your site was the 2nd result on Google.

I just wanted to share an updated method for skewing objects in Inkscape that I later found on YouTube:
https://www.youtube.com/watch?v=Thy_YCi8dXA

**Comment by Roy-Torley** [comment]
Hello Candide U,
Belated Happy New Year!  Thank you for your note!  I took a look at Nick
Sapolito's tutorial and I like what I see.  I have looked at many of his
videos and enjoy his teaching style.  I recommend that you keep on watching
and learn and grow from what he shows.

I am familiar with the Deformation Envelope feature that the latest
versions of Inkscape have.  A more primitive version of it exists in
Version 1.01, which is the version I used when I made my tutorials.
Inkscape updated to Version 1.2 at about the same time that I finished
writing the tutorial, making the latter outdated almost immediately (hmm,
updated, outdated, there must be a pun there somewhere).

I have chosen not to update my tutorials owing to work and a few major
projects that keep me well occupied.  I keep the tutorials online because I
believe that they can still serve as a good place from where you can launch
yourself into beginning graphic design, even if you don't have a background
in it.  Once you feel comfortable with what you have accomplished, you can
then move on to bigger and more imaginative concepts.

Once again, thank you for sending me the kind note.

I wish you good health, good fortune, and a great New Year,

- Roy


www.songbookus.com
***@***.***

**Comment by candideu** [comment]
Hi Roy! 

Happy belated New Year to you too! Thanks for the kind note and for your helpful Inkscape resources. I'm glad I stumbled on your tutorials.

All the best,

Candide
